### PR TITLE
Rename Brush names

### PR DESCRIPTION
**Pull request by JanTamis**
#277

### CODE REVIEW

**Comment by JanTamis** [comment]
@SKProCH Please let me know if I am renaming the correct properties

**Comment by SKProCH** [comment]
I hadn't thought about renaming the property names, actually. However, let's keep the new names, I think it's the right thing to do. We should also rename ValidationErrorColor. 

But the most important thing is to rename 
- https://github.com/AvaloniaCommunity/Material.Avalonia/blob/master/Material.Styles/Themes/Base/MaterialPredefinedBaseColors.axaml
- https://github.com/AvaloniaCommunity/Material.Avalonia/blob/master/Material.Styles/Themes/ResourceDictionaryThemeExtensions.cs
- https://github.com/AvaloniaCommunity/Material.Avalonia/blob/master/Material.Styles/Themes/MaterialThemeBase.cs#L72

And according to the renaming of these styles, also rename all their names in all style files (rename all old resources names across solution). 

However, if you don't want to do that, fine, we can dump this PR as it is.

**Review by SKProCH — APPROVED** [review]

**Comment by JanTamis** [comment]
I am willing to rename all the styles 🙂. Just needed to know if I was on the right track.

**Comment by JanTamis** [comment]
@SKProCH Please let me know if there are areas I missed

**Comment by SKProCH** [comment]
Seems like everything is fine.

But also I noticed that we can actually remove Hue from PrimaryHueLightBrush. So it will be MaterialPrimaryLightBrush. What do you think?

**Comment by SKProCH** [comment]
Also, can you please add a note with name changes? 
Like:
- Old -> New

This needs to be included to migration guide. 

Also, if you can (and you want) it will be nice to have fallback brushes resources with old names. Just a resource dictionary with old names, which will be referencing new brushes (or new brushes colors)

**Comment by JanTamis** [comment]
> Seems like everything is fine.
> 
> But also I noticed that we can actually remove Hue from PrimaryHueLightBrush (and similar brushes). So it will be MaterialPrimaryLightBrush. What do you think?

I think that that is a great idea

**Comment by JanTamis** [comment]
> Also, can you please add a note with name changes? Like:
> 
> * Old -> New
> 
> This needs to be included to migration guide.
> 
> Also, if you can (and you want) it will be nice to have fallback brushes resources with old names. Just a resource dictionary with old names, which will be referencing new brushes (or new brushes colors)

Where would you like me to add the notes to?

**Comment by SKProCH** [comment]
> > Also, can you please add a note with name changes? Like:
> > 
> > * Old -> New
> > 
> > This needs to be included to migration guide.
> > Also, if you can (and you want) it will be nice to have fallback brushes resources with old names. Just a resource dictionary with old names, which will be referencing new brushes (or new brushes colors)
> 
> Where would you like me to add the notes to?

Just paste it here

**Comment by JanTamis** [comment]
> Also, can you please add a note with name changes? Like:
> 
> * Old -> New
> 
> This needs to be included to migration guide.
> 
> Also, if you can (and you want) it will be nice to have fallback brushes resources with old names. Just a resource dictionary with old names, which will be referencing new brushes (or new brushes colors)

I unfortunately do not know how to add fallback brushes 😅

**Comment by JanTamis** [comment]
> > > Also, can you please add a note with name changes? Like:
> > > 
> > > * Old -> New
> > > 
> > > This needs to be included to migration guide.
> > > Also, if you can (and you want) it will be nice to have fallback brushes resources with old names. Just a resource dictionary with old names, which will be referencing new brushes (or new brushes colors)
> > 
> > 
> > Where would you like me to add the notes to?
> 
> Just paste it here

okay

**Comment by SKProCH** [comment]
> > Also, can you please add a note with name changes? Like:
> > 
> > * Old -> New
> > 
> > This needs to be included to migration guide.
> > 
> > Also, if you can (and you want) it will be nice to have fallback brushes resources with old names. Just a resource dictionary with old names, which will be referencing new brushes (or new brushes colors)
> 
> I unfortunately do not know how to add fallback brushes 😅

Okay, no problem, I'll try to do it myself, after PR merge

**Comment by JanTamis** [comment]
### Brushes
- PrimaryHueLightBrush -> MaterialPrimaryLightBrush
- PrimaryHueLightForegroundBrush -> MaterialPrimaryLightForegroundBrush
- PrimaryHueMidBrush -> MaterialPrimaryMidBrush
- PrimaryHueMidForegroundBrush -> MaterialPrimaryMidForegroundBrush
- PrimaryHueDarkBrush -> MaterialPrimaryDarkBrush
- PrimaryHueDarkForegroundBrush -> MaterialPrimaryForegroundBrush

- SecondaryHueLightBrush -> MaterialSecondaryLightBrush
- SecondaryHueLightForegroundBrush -> MaterialSecondaryLightForegroundBrush
- SecondaryHueMidBrush -> MaterialSecondaryMidBrush
- SecondaryHueDarkBrush -> MaterialSecondaryDarkBrush
- SecondaryHueDarkForegroundBrush -> MaterialSecondaryDarkForegroundBrush

- ValidationErrorBrush -> MaterialValidationErrorBrush

- MaterialDesignBackground -> MaterialBackgroundBrush
- MaterialDesignPaper -> MaterialPaperBrush
- MaterialDesignCardBackground -> MaterialCardBackgroundBrush
- MaterialDesignToolBarBackground -> MaterialToolBarBackgroundBrush
- MaterialDesignBody -> MaterialBodyBrush
- MaterialDesignBodyLight -> MaterialBodyLightBrush
- MaterialDesignColumnHeader -> MaterialColumnHeaderBrush
- MaterialDesignCheckBoxOff -> MaterialCheckBoxOffBrush
- MaterialDesignCheckBoxDisabled -> MaterialCheckBoxDisabledBrush
- MaterialDesignTextBoxBorder -> MaterialTextBoxBorderBrush
- MaterialDesignDivider -> MaterialDividerBrush
- MaterialDesignSelection -> MaterialSelectionBrush
- MaterialDesignToolForeground -> MaterialToolForegroundBrush
- MaterialDesignToolBackground -> MaterialToolBackgroundBrush
- MaterialDesignFlatButtonClick -> MaterialFlatButtonClickBrush
- MaterialDesignFlatButtonRipple -> MaterialFlatButtonRippleBrush
- MaterialDesignToolTipBackground -> MaterialToolTipBackgroundBrush
- MaterialDesignChipBackground -> MaterialChipBackgroundBrush
- MaterialDesignSnackbarBackground -> MaterialSnackbarBackgroundBrush
- MaterialDesignSnackbarMouseOver -> MaterialSnackbarMouseOverBrush
- MaterialDesignSnackbarRipple -> MaterialSnackbarRippleBrush
- MaterialDesignTextFieldBoxBackground -> MaterialTextFieldBoxBackgroundBrush
- MaterialDesignTextFieldBoxHoverBackground -> MaterialTextFieldBoxHoverBackgroundBrush
- MaterialDesignTextFieldBoxDisabledBackground -> MaterialTextFieldBoxDisabledBackgroundBrush
- MaterialDesignTextAreaBorder -> MaterialTextAreaBorderBrush
- MaterialDesignTextAreaInactiveBorder -> MaterialTextAreaInactiveBorderBrush
- MaterialDesignDataGridRowHoverBackground -> MaterialDataGridRowHoverBackgroundBrush

### Colors
- ValidationErrorColor -> MaterialValidationErrorColor
- MaterialDesignBackground -> MaterialBackgroundColor
- MaterialDesignPaper -> MaterialPaperColor
- MaterialDesignCardBackground -> MaterialCardBackgroundColor
- MaterialDesignToolBarBackground -> MaterialToolBarBackgroundColor
- MaterialDesignBody -> MaterialBodyColor
- MaterialDesignBodyLight -> MaterialBodyLightColor
- MaterialDesignColumnHeader -> MaterialColumnHeaderColor
- MaterialDesignCheckBoxOff -> MaterialCheckBoxOffColor
- MaterialDesignCheckBoxDisabled -> MaterialCheckBoxDisabledColor
- MaterialDesignTextBoxBorder -> MaterialTextBoxBorderColor
- MaterialDesignDivider -> MaterialDividerColor
- MaterialDesignSelection -> MaterialSelectionColor
- MaterialDesignToolForeground -> MaterialToolForegroundColor
- MaterialDesignToolBackground -> MaterialToolBackgroundColor
- MaterialDesignFlatButtonClick -> MaterialFlatButtonClickColor
- MaterialDesignFlatButtonRipple -> MaterialFlatButtonRippleColor
- MaterialDesignToolTipBackground -> MaterialToolTipBackgroundColor
- MaterialDesignChipBackground -> MaterialChipBackgroundColor
- MaterialDesignSnackbarBackground -> MaterialSnackbarBackgroundColor
- MaterialDesignSnackbarMouseOver -> MaterialSnackbarMouseOverColor
- MaterialDesignSnackbarRipple -> MaterialSnackbarRippleColor
- MaterialDesignTextFieldBoxBackground -> MaterialTextFieldBoxBackgroundColor
- MaterialDesignTextFieldBoxHoverBackground -> MaterialTextFieldBoxHoverBackgroundColor
- MaterialDesignTextFieldBoxDisabledBackground -> MaterialTextFieldBoxDisabledBackgroundColor
- MaterialDesignTextAreaBorder -> MaterialTextAreaBorderColor
- MaterialDesignTextAreaInactiveBorder -> MaterialTextAreaInactiveBorderColor
- MaterialDesignDataGridRowHoverBackground -> MaterialDataGridRowHoverBackgroundColor

**Comment by SKProCH** [comment]
Yep, seems like everything is fine, thanks. Should I merge right now?

**Comment by JanTamis** [comment]
yes, your welcome

**Comment by SKProCH** [comment]
Thanks. I actually can give write permissions for the repo if you want to contribute further.

**Comment by JanTamis** [comment]
That would be useful.

**Comment by SKProCH** [comment]
Invited you. Did you have any messenger such as telegram or discord, etc?

**Comment by JanTamis** [comment]
I have discord

**Pull request merged**
