### PR TITLE
Migrate_Combobox

### PR DESCRIPTION
**Pull request by JanTamis**
#233

### CODE REVIEW

**Review by SKProCH — APPROVED** [review]

**Comment by SKProCH** [comment]
I have some drafts for ComboBoxes. I'll push it to this branch, but feel free to change everything, since not everything works properly

**Comment by JanTamis** [comment]
Ill take a look

**Comment by JanTamis** [comment]
> I have some drafts for ComboBoxes. I'll push it to this branch, but feel free to change everything, since not everything works properly

can you tell me what doesn't work?

**Comment by SKProCH** [comment]
Triangle missing in the default style. Also, seems like the outline style has incorrect clipping for frame/border (proper variant implemented in TextBox outlines style). Probably some watermark/label problems.

**Comment by JanTamis** [comment]
> Triangle missing in the default style. Also, seems like the outline style has incorrect clipping for frame/border (proper variant implemented in TextBox outlines style). Probably some watermark/label problems.

@SKProCH Can you check if the bugs are resolved?

**Comment by SKProCH** [comment]
> > Triangle missing in the default style. Also, seems like the outline style has incorrect clipping for frame/border (proper variant implemented in TextBox outlines style). Probably some watermark/label problems.
> 
> @SKProCH Can you check if the bugs are resolved?

Yep, a little later

**Comment by SKProCH** [comment]
Probably default combobox too tall - even compared with Filled. Everything else is fine

**Comment by JanTamis** [comment]
> Probably default combobox too tall - even compared with Filled. Everything else is fine

How tall would you like it to be?

**Comment by SKProCH** [comment]
> > Probably default combobox too tall - even compared with Filled. Everything else is fine
> 
> How tall would you like it to be?

Probably same size of textbox i suppose

**Comment by JanTamis** [comment]
image
Is this okay?

**Comment by SKProCH** [comment]
Yep. Thanks!

**Comment by JanTamis** [comment]
Ill take a short look if I can resolve it.

**Comment by JanTamis** [comment]
so I taken a look but I couldn't figure it out, so it can be merged.

**Pull request merged**
